CREATE TABLE IF NOT EXISTS channels (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type ENUM('main', 'secondary') NOT NULL,
    channel_id VARCHAR(255) NOT NULL UNIQUE,
    language VARCHAR(10) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
ALTER TABLE channels ADD UNIQUE KEY (channel_id);
